// @ts-nocheck
// This file is autogenerated by Firebase Studio. Do not edit.

export const firebaseConfig = {
  "projectId": "studio-7977561804-6ad71",
  "appId": "1:245163195414:web:954fe100ddfabc2159c937",
  "apiKey": "AIzaSyA4KyoadJIgtwNH8EwGS-GqwchdTUJ-AQc",
  "authDomain": "studio-7977561804-6ad71.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "245163195414"
};
